apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: log-parser-service-monitor
  namespace: monitoring
  labels:
    prometheus: main
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: web
      path: /metrics
  selector:
    matchLabels:
      app: log-parser
