apiVersion: v1
kind: Service
metadata:
  name: log-parser-service
  namespace: monitoring
  labels:
    job: log-parser-job
    app: log-parser
spec:
  type: ClusterIP
  selector:
    app: log-parser
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
