apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
  name: decoding-sdk-rules
spec:
  groups:
    - name: critical-group
      rules:
        - alert: InstanceDown
          expr: up == 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: Prometheus target down {{ $labels.instance }}
    - name: moderate-group
      rules:
        - alert: HighRequestFailure
          expr: sum(rate(decoding_requests_successful[5m])) / (sum(rate(decoding_requests_failed[5m])) + sum(rate(decoding_requests_successful[5m]))) * 100 > 5
          for: 5m
          labels:
            severity: moderate
          annotations:
            summary: High number of failed requests in the past 5 minutes
            description: "The number of failed requests is more than 5% in the past 5 minutes."
        - alert: HighRequestlatency
          expr: histogram_quantile(0.5, sum(latency_milliseconds_bucket) by (le)) > 200
          for: 5m
          labels:
            severity: moderate
          annotations:
            summary: High request latency in the past 5 minutes
