apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-metrics-exporter-deployment
  namespace: monitoring
  labels:
    app: custom-metrics-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics-exporter
  template:
    metadata:
      labels:
        app: custom-metrics-exporter
    spec:
      serviceAccountName: custom-metrics-exporter
      containers:
      - name: custom-metrics-exporter
        image: niflnir/custom-metrics-exporter:v1.0.0
        ports:
        - name: metrics
          containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 1Gi
            cpu: 500m
