apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-exporter-service
  namespace: monitoring
  labels:
    job: custom-metrics-exporter-job
    app: custom-metrics-exporter
spec:
  type: ClusterIP
  selector:
    app: custom-metrics-exporter
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
