apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: production
  namespace: monitoring
spec:
  version: v2.50.1
  serviceAccountName: prometheus
  podMonitorSelector: {}
  podMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      prometheus: main
  serviceMonitorNamespaceSelector: {}
  alerting: 
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-operated
      port: 9093
  ruleSelector: {}
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 2Gi
  replicas: 2
  logLevel: info
  logFormat: logfmt
  retention: 6h
  scrapeInterval: 15s
  securityContext:
    fsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 10Gi
  remoteWrite:
    - url: http://receiver-write.monitoring.svc.cluster.local:10908/api/v1/receive
      queueConfig:
        maxSamplesPerSend: 1000
        maxShards: 200
        capacity: 2500
  replicaExternalLabelName: __replica__
