apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
  name: bob-rules
spec:
  groups:
    - name: bob
      rules:
        - alert: bob
          expr: decoding_requests_successful_total == 1
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: BOB
