{
 "title": "Decoding SDK dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Number of Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum(decoding_requests_failed) by (type) + sum(decoding_requests_successful) by (type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Successful Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "1535 / (sum(decoding_requests_failed) by (type) + sum(decoding_requests_successful) by (type)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "0 / (sum(decoding_requests_failed) by (type) + sum(decoding_requests_successful) by (type)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(latency_milliseconds_bucket) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(latency_milliseconds_bucket) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Decoding sdk server logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{app=\"decoding-sdk-server\"} |= ``"
    }
   ]
  },
  {
   "title": "Decoding sdk worker logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{app=\"decoding-sdk-worker\"} |= ``"
    }
   ]
  }
 ]
}