apiVersion: v1
kind: Service
metadata:
  name: decoding-sdk-server-service
  namespace: decoding-sdk
  labels:
    app: decoding-sdk-server
spec:
  selector:
    app: decoding-sdk-server
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010
      nodePort: 30080
  type: NodePort
