---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: querier
spec:
  type: ClusterIP
  ports:
    - port: 10901
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: querier
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: querier-console
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30002
  selector:
    app.kubernetes.io/name: querier
